---

# Operaciones comunes sobre todos los nodos
- import_playbook: playbook/common.yml

# Configuración específica de los servidores DNS
- import_playbook: playbook/dns.yml

# Configuración específica de los nodos
- import_playbook: playbook/dns-client.yml

# Configuración específica de los servidores HTTP
- import_playbook: playbook/http.yml

# Configuración específica de Corosync y Pacemaker
- import_playbook: playbook/cluster.yml

# Iniciar cluster
- import_playbook: playbook/cluster_start.yml

