- hosts:
    - nodo1
    - nodo2

  gather_facts: true
  remote_user: vagrant
  become: yes
  become_user: root
  become_method: sudo

  # Desactivar ejecución en paralelo para evitar problemas con Vagrant-Cachier
  serial: 1


  tasks:
    # Instalación
    - name: Instalar servicio HTTP
      apt: pkg={{ item }} state=present
      with_items:
        - apache2
        - apache2-utils
      notify: start apache

    # Configuración del nombre por defecto del servidor web
    - name: Configurar FQDN por defecto
      template: src=apache/fqdn.conf.j2
        dest=/etc/apache2/conf-available/fqdn.conf
        owner=root group=root mode=0644
      notify: restart apache

    - name: Habilitar configuración FQDN
      command: a2enconf fqdn.conf
      notify: restart apache

    # Configurar y habilitar un sitio vitual por nombre
    - name: Configurar sitio web
      template: src=apache/website.conf.j2
        dest=/etc/apache2/sites-available/{{ equipo }}.conf
        owner=root group=root mode=0644
      notify: restart apache

    - name: Habilitar configuración de sitio web
      command: a2ensite {{ equipo }}.conf
      notify: restart apache

    - name: Deshabilitar el sitio web por defecto
      command: a2dissite 000-default
      notify: restart apache

    # Acondicionar directorio del sitio y crear página inicial
    - name: Crear directorio raíz para el sitio
      file: path=/var/www/{{ equipo }}
        state=directory recurse=yes
        owner=www-data group=www-data mode=0775

    - name: Configurar página inicial
      template: src=apache/index.html.j2
        dest=/var/www/{{ equipo }}/index.html
        owner=www-data group=www-data mode=0664


  handlers:
    - name: start apache
      systemd: name=apache2 state=started

    - name: restart apache
      systemd: name=apache2 state=restarted

